print('What do you get when you cross a snowman with a vampire?')
input()
print('Frostbite!')
input()
# escape characters
print('What do dentists call a astronaut\'s cavity?')
input()
print('A Black hole!')
input()
print('Knock Knock')
input()
# quotes and double quotes
print("Who's there?")
input()
print("Interrupting cow.")
input()
print("Interrupting cow wh.", end='')
print('-MOO!')
